import { useState, useEffect, useCallback } from 'react';
import StatusBadge from '../components/ui/StatusBadge';
import Button from '../components/ui/Button';
import { api } from '../lib/api';
import './Dashboard.css';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function getDaysInMonth(year, month) {
  return new Date(year, month + 1, 0).getDate();
}

function getFirstDayOfMonth(year, month) {
  return new Date(year, month, 1).getDay();
}

export default function ComplianceCalendar() {
  const [currentDate, setCurrentDate] = useState(() => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1); });
  const [deadlines, setDeadlines] = useState([]);
  const [selected, setSelected] = useState(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  const year = currentDate.getFullYear();
  const month = currentDate.getMonth();

  const load = useCallback(async () => {
    setError('');
    try {
      const from = new Date(year, month, 1).toISOString();
      const to = new Date(year, month + 1, 0, 23, 59).toISOString();
      const { deadlines } = await api.listDeadlines({ from, to });
      setDeadlines(deadlines);
    } catch (err) {
      setError(err.message);
    }
  }, [year, month]);

  useEffect(() => { load(); setSelected(null); }, [load]);

  const daysInMonth = getDaysInMonth(year, month);
  const firstDay = getFirstDayOfMonth(year, month);
  const days = [];
  for (let i = 0; i < firstDay; i++) days.push(null);
  for (let d = 1; d <= daysInMonth; d++) days.push(d);

  const eventsByDay = {};
  for (const dl of deadlines) {
    const day = new Date(dl.dueDate).getDate();
    (eventsByDay[day] = eventsByDay[day] || []).push(dl);
  }

  const markDone = async (dl, status) => {
    setBusy(true);
    try {
      await api.setDeadlineStatus(dl.id, status);
      await load();
      setSelected((s) => (s && s.id === dl.id ? { ...s, status } : s));
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  };

  const statusColor = (s) => (s === 'DONE' ? 'safe' : s === 'OVERDUE' ? 'danger' : 'warn');

  return (
    <div>
      <div className="app-main__header">
        <h1 className="app-main__greeting">Compliance Calendar</h1>
        <p className="app-main__subtitle">
          Statutory deadlines for all your clients — generated by rules, not guesswork. Mark filings done as you complete them.
        </p>
      </div>

      {error && (
        <div className="page-panel" style={{ borderColor: 'var(--status-danger)', marginBottom: 'var(--space-4)', padding: 'var(--space-4)' }}>
          <span style={{ color: 'var(--status-danger)', fontSize: 'var(--text-sm)' }}>{error}</span>
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 'var(--space-6)', alignItems: 'flex-start' }}>
        {/* Calendar grid */}
        <div className="page-panel">
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'var(--space-6)' }}>
            <button
              onClick={() => setCurrentDate(new Date(year, month - 1, 1))}
              style={{ background: 'var(--bg-deep)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '8px 12px', color: 'var(--text-secondary)', cursor: 'pointer' }}
            >
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M10 3L5 8l5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
            </button>
            <h4>{MONTHS[month]} {year}</h4>
            <button
              onClick={() => setCurrentDate(new Date(year, month + 1, 1))}
              style={{ background: 'var(--bg-deep)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--radius-md)', padding: '8px 12px', color: 'var(--text-secondary)', cursor: 'pointer' }}
            >
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M6 3l5 5-5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '1px', background: 'var(--border-subtle)', borderRadius: 'var(--radius-md)', overflow: 'hidden' }}>
            {DAYS.map((d) => (
              <div key={d} style={{ padding: 'var(--space-3)', textAlign: 'center', fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--text-muted)', background: 'var(--bg-deep)', textTransform: 'uppercase', letterSpacing: 'var(--tracking-wider)' }}>
                {d}
              </div>
            ))}
            {days.map((day, i) => {
              const events = day ? eventsByDay[day] : null;
              return (
                <div
                  key={i}
                  onClick={() => events && setSelected(events[0])}
                  style={{
                    padding: 'var(--space-2)',
                    minHeight: '84px',
                    background: 'var(--bg-surface)',
                    cursor: events ? 'pointer' : 'default',
                  }}
                  onMouseEnter={(e) => { if (events) e.currentTarget.style.background = 'var(--bg-elevated)'; }}
                  onMouseLeave={(e) => { e.currentTarget.style.background = 'var(--bg-surface)'; }}
                >
                  {day && (
                    <>
                      <span style={{ fontSize: 'var(--text-sm)', color: events ? 'var(--text-primary)' : 'var(--text-muted)', fontWeight: events ? 600 : 400 }}>
                        {day}
                      </span>
                      {events && events.slice(0, 2).map((ev) => (
                        <div
                          key={ev.id}
                          onClick={(e) => { e.stopPropagation(); setSelected(ev); }}
                          style={{
                            marginTop: '4px',
                            padding: '2px 6px',
                            fontSize: '10px',
                            fontWeight: 600,
                            borderRadius: 'var(--radius-sm)',
                            background: ev.status === 'DONE' ? 'rgba(46, 204, 113, 0.15)' : ev.status === 'OVERDUE' ? 'rgba(231, 76, 60, 0.15)' : 'rgba(243, 156, 18, 0.15)',
                            color: ev.status === 'DONE' ? 'var(--status-safe)' : ev.status === 'OVERDUE' ? 'var(--status-danger)' : 'var(--status-warn)',
                            whiteSpace: 'nowrap',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                          }}
                          title={`${ev.title} — ${ev.client.name}`}
                        >
                          {ev.title}
                        </div>
                      ))}
                      {events && events.length > 2 && (
                        <span style={{ fontSize: '10px', color: 'var(--text-muted)' }}>+{events.length - 2} more</span>
                      )}
                    </>
                  )}
                </div>
              );
            })}
          </div>
          {deadlines.length === 0 && (
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginTop: 'var(--space-4)', textAlign: 'center' }}>
              No deadlines this month. Add clients to populate their statutory calendar automatically.
            </p>
          )}
        </div>

        {/* Detail panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          <div className="page-panel">
            <div className="page-panel__header">
              <span className="page-panel__title">Deadline Details</span>
            </div>
            {selected ? (
              <div>
                <strong style={{ fontSize: 'var(--text-base)', color: 'var(--text-primary)', display: 'block', marginBottom: 'var(--space-2)' }}>
                  {selected.title}
                </strong>
                <div style={{ display: 'flex', gap: 'var(--space-2)', marginBottom: 'var(--space-3)' }}>
                  <StatusBadge status={statusColor(selected.status)}>
                    {selected.status === 'DONE' ? 'Filed' : selected.status === 'OVERDUE' ? 'Overdue' : 'Upcoming'}
                  </StatusBadge>
                </div>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)', marginBottom: 'var(--space-2)' }}>
                  <strong style={{ color: 'var(--text-primary)' }}>Client:</strong> {selected.client.name}
                </p>
                <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)', marginBottom: 'var(--space-2)' }}>
                  <strong style={{ color: 'var(--text-primary)' }}>Due:</strong> {new Date(selected.dueDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
                </p>
                {selected.description && (
                  <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginTop: 'var(--space-3)', lineHeight: 1.6 }}>
                    {selected.description}
                  </p>
                )}
                <div style={{ marginTop: 'var(--space-5)' }}>
                  {selected.status !== 'DONE' ? (
                    <Button variant="primary" size="sm" onClick={() => markDone(selected, 'DONE')} disabled={busy}>
                      Mark as Filed
                    </Button>
                  ) : (
                    <Button variant="ghost" size="sm" onClick={() => markDone(selected, 'UPCOMING')} disabled={busy}>
                      Reopen
                    </Button>
                  )}
                </div>
              </div>
            ) : (
              <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)' }}>
                Click a calendar event to view details and mark it filed.
              </p>
            )}
          </div>

          <div className="page-panel">
            <div className="page-panel__header">
              <span className="page-panel__title">This Month</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              {['UPCOMING', 'OVERDUE', 'DONE'].map((status) => {
                const count = deadlines.filter((dl) => dl.status === status).length;
                return (
                  <div key={status} style={{ display: 'flex', justifyContent: 'space-between', padding: 'var(--space-2) var(--space-3)', background: 'var(--bg-deep)', borderRadius: 'var(--radius-md)' }}>
                    <span style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>
                      {status === 'DONE' ? 'Filed' : status === 'OVERDUE' ? 'Overdue' : 'Upcoming'}
                    </span>
                    <strong style={{ fontSize: 'var(--text-sm)', color: status === 'OVERDUE' && count > 0 ? 'var(--status-danger)' : 'var(--text-primary)' }}>{count}</strong>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
